### ISSUE TITLE
Change "File in Bugzilla" to "View in Bugzilla" when bug already exists

### ISSUE THREAD

**Issue by Osmose** [Osmose/webext-nightly-js-errors#2]
The file a bug button should be smart enough to know when it was already used to file a bug in Bugzilla. If it finds a matching bug, it should change to a "View in Bugzilla" button to avoid double-filings.

Maybe the text should include the bug number? Like "View Bug 1234567".

**Comment by mythmon** [comment]
This could work via a localstorage flag. If you want to be extra clever, it could search for the whiteboard flags that are included in bugs default. That would also allow multiple issues to all correspond to the same bug.

**Comment by Osmose** [comment]
I have a commit that does this via the Bugzilla API, but it needs some refactoring (and in fact the whole extension needs refactoring but whatever): https://github.com/Osmose/webext-nightly-js-errors/commit/30cf45cfad8dc77ea918c20a0319ffcbeaa9ce36
