### ISSUE TITLE
File in Bugzilla assumes Firefox product

### ISSUE THREAD

**Issue by jryans** [Osmose/webext-nightly-js-errors#4]
Not all issues belong in the Firefox product in Bugzilla. For example, some may go to Toolkit or Core.

The DevTools team is also plotting to move to their own Bugzilla product as well, so this soon affect nearly all bugs I might file from here.

**Comment by Osmose** [comment]
Thanks for the report!

You should be able to change the product after clicking the link. Otherwise I'm not sure how we'd determine which product to use for the error. Maybe a mapping we ship with the add-on? Seems like a bit of a pain to maintain, though.

**Comment by jryans** [comment]
> You should be able to change the product after clicking the link.

Bugzilla seems to prevent changing the product directly on the filing page for this type of URL. Maybe that should be treated as a Bugzilla UX problem... Currently the workarounds appear to be:

1. Notice the wrong product immediately and edit the URL to the correct product (which implies reloading the page and discarding all other fields)
2. File anyway in the wrong product and then move the bug afterwards (this means component watchers won't see the initial bug mail, which is unfortunate)

> Otherwise I'm not sure how we'd determine which product to use for the error. Maybe a mapping we ship with the add-on? Seems like a bit of a pain to maintain, though.

I am not too sure what to recommend either, I guess... Looking at the [Crash Report UI](https://crash-stats.mozilla.com/report/index/768b0ca2-1625-49f9-aa54-e35b10180329#tab-bugzilla) for ideas here, it appears they try to guess common products and offer several options:

![image](https://user-images.githubusercontent.com/279572/38110500-8890c372-3361-11e8-8bc2-876316050a96.png)

Maybe the "File Bug" button could have a menu to pick the product...?
